### ISSUE TITLE
Is this still recommended?

### ISSUE THREAD

**Issue by abrambailey** [internalfx/quickshot#49]
This project looks like it is not actively developed, while Theme Kit is. Are there any advantages to quickshot, and is it recommended still?

**Comment by internalfx** [comment]
@abrambailey I am not familiar enough to comment on theme kit. But you are right, quickshot is not actively developed.

As far as being recommended, that depends. If there was another developer willing to work on quickshot I would hand over the reigns.

**Comment by panoply** [comment]
While theme kit is the stock standard for Shopify Theme Development, it still doesn't really match the power of Quickshot and while Quickshot is not actively developed it's not by any means dead and still outperforms theme kit in terms of upload speed and being a completely node dependant module makes it a huge draw card. 

One of the main issues we have faced using theme kit is its inability to handle multiple store uploads. Our company (a European fashion brand) face major issues with Shopify due to the platform being unable to cater to multiple currencies at checkout level, thus we operate multiple stores in multiple currencies. Using theme kit we are unable to keep the themes in sync across all stores and this is where Quickshot truly caters to our needs.

Internally, we have a highly modified fork of Quickshot that has been stripped down to handle only upload, download and watching because our development uses a series of Gulp tasks and [Rollup](https://rollupjs.org/guide/en) to handle bundling of assets and views from a `src` directory into a `theme` directory. 

The main stand-out features with theme kit is the local development and livereload implementation which is not very hard to achieve using a BrowserSync proxy with Quickshot anyway.

**Comment by internalfx** [comment]
Honestly, I'm surprised that after all this time it's even still relevant. I would have expected Shopify to produce something far better than me. They simply have more resources (and incentive) to create the best development tools around.

I'm at a point in my life (with a wife, and kids) where working on OSS for free is not something I have much ability to do. If Shopify (or some other entity) wanted to sponsor it's development, then maybe Quickshot could be made better than ever.

@panoply I'm glad Quickshot has helped you.
