### ISSUE TITLE
Show liquid errors.

### ISSUE THREAD

**Issue by internalfx** [internalfx/quickshot#64]
> when it comes to liquid errors, it simply reads undefined. So it takes removing chunks of code to isolate the error.

@valespring

Can you verify this is still the case?

I have done quite a bit of work to show better errors in v3

**Comment by valespring** [comment]
@internalfx My apologies, I haven't gotten much face time with the new version since I was simply updating them for automatic deployment via Codeship - the builds were failing. I can update this issue thread as I utilize QS, I just did a quick test with a section schema and it looks like it shows the actual error instead of 'undefined'.

**Comment by internalfx** [comment]
Nice, feel free to re-open if the you encounter that issue again.
